name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install CPU torch in order to avoid disk space issues
          python -m pip install -e .[dev] --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Black (format check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy
        run: mypy src
